# Generated by Django 6.1.1 on 2026-09-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerbalAutopsy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age_at_death', models.IntegerField()),
                ('date_of_death', models.DateField()),
                ('place_of_death', models.CharField(choices=[('HO', 'Home'), ('HP', 'Hospital'), ('O', 'Other')], max_length=2)),
                ('respondent_name', models.CharField(max_length=100)),
                ('respondent_relationship', models.CharField(max_length=100)),
                ('interview_date', models.DateField()),
                ('symptoms', models.TextField()),
                ('probable_cause_of_death', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
